version: '2.1'
services:

    # PowerAuth 2.0 Server Database
    powerauth-mysql:
        image: powerauth-server-mysql
        container_name: powerauth-server-mysql
        ports:
            - "23316:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${POWERAUTH_MYSQL_PASSWORD}
        volumes:
            - ${POWERAUTH_MYSQL_PATH}:/var/lib/mysql
        healthcheck:
            test: mysqladmin -uroot -p${POWERAUTH_MYSQL_PASSWORD} ping
            interval: 5s
            timeout: 5s
            retries: 30

    # PowerAuth 2.0 Push Server Database
    powerauth-push-mysql:
        image: powerauth-push-mysql
        container_name: powerauth-push-mysql
        ports:
            - "23336:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${POWERAUTH_PUSH_MYSQL_PASSWORD}
        volumes:
            - ${POWERAUTH_PUSH_MYSQL_PATH}:/var/lib/mysql
        healthcheck:
            test: mysqladmin -uroot -p${POWERAUTH_PUSH_MYSQL_PASSWORD} ping
            interval: 5s
            timeout: 5s
            retries: 30

    # PowerAuth 2.0 WebFlow MySQL Database
    powerauth-webflow-mysql:
        image: powerauth-webflow-mysql
        container_name: powerauth-webflow-mysql
        ports:
            - "23376:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${POWERAUTH_WEBFLOW_MYSQL_PASSWORD}
        volumes:
            - ${POWERAUTH_WEBFLOW_MYSQL_PATH}:/var/lib/mysql
        healthcheck:
            test: mysqladmin -uroot -p${POWERAUTH_WEBFLOW_MYSQL_PASSWORD} ping
            interval: 5s
            timeout: 5s
            retries: 30

    # PowerAuth 2.0 Server
    powerauth-java-server:
        image: powerauth-server
        container_name: powerauth-server
        ports:
            - "20010:8080"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/powerauth-java-server"]
            interval: 10s
            timeout: 10s
            retries: 30
        environment:
            - DB_POWERAUTH_SERVER_URL=${DB_POWERAUTH_SERVER_URL}
            - DB_POWERAUTH_SERVER_USERNAME=${DB_POWERAUTH_SERVER_USERNAME}
            - DB_POWERAUTH_SERVER_PASSWORD=${DB_POWERAUTH_SERVER_PASSWORD}
            - DB_POWERAUTH_SERVER_DRIVER=${DB_POWERAUTH_SERVER_DRIVER}
            - POWERAUTH_SERVICE_URL=${POWERAUTH_SERVICE_URL}
            - POWERAUTH_SERVICE_SECURITY_TOKEN=${POWERAUTH_SERVICE_SECURITY_TOKEN}
            - POWERAUTH_SERVICE_SECURITY_SECRET=${POWERAUTH_SERVICE_SECURITY_SECRET}
        depends_on:
            powerauth-mysql:
                condition: service_healthy

    # PowerAuth 2.0 Push Server
    powerauth-push-server:
        image: powerauth-push-server
        container_name: powerauth-push-server
        ports:
            - "20030:8080"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/powerauth-push-server"]
            interval: 10s
            timeout: 10s
            retries: 30
        environment:
            - POWERAUTH_SERVICE_URL=${POWERAUTH_SERVICE_URL}
            - DB_PUSH_SERVER_URL=${DB_PUSH_SERVER_URL}
            - DB_PUSH_SERVER_USERNAME=${DB_PUSH_SERVER_USERNAME}
            - DB_PUSH_SERVER_PASSWORD=${DB_PUSH_SERVER_PASSWORD}
            - DB_PUSH_SERVER_DRIVER=${DB_PUSH_SERVER_DRIVER}
        depends_on:
            powerauth-push-mysql:
                condition: service_healthy
            powerauth-java-server:
                condition: service_healthy

    # PowerAuth 2.0 NextStep Server
    powerauth-nextstep:
        image: powerauth-nextstep
        container_name: powerauth-nextstep
        ports:
            - "13010:8080"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/powerauth-nextstep"]
            interval: 10s
            timeout: 10s
            retries: 30
        environment:
            - DB_NEXTSTEP_URL=${DB_NEXTSTEP_URL}
            - DB_NEXTSTEP_USERNAME=${DB_NEXTSTEP_USERNAME}
            - DB_NEXTSTEP_PASSWORD=${DB_NEXTSTEP_PASSWORD}
            - DB_NEXTSTEP_DRIVER=${DB_NEXTSTEP_DRIVER}
        depends_on:
            powerauth-webflow-mysql:
                condition: service_healthy

    # PowerAuth 2.0 Web Flow Server
    powerauth-webflow:
        image: powerauth-webflow
        container_name: powerauth-webflow
        ports:
            - "13030:8080"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/powerauth-webflow"]
            interval: 10s
            timeout: 10s
            retries: 30
        environment:
            - DB_DATA_ADAPTER_URL=${DB_DATA_ADAPTER_URL}
            - DB_DATA_ADAPTER_USERNAME=${DB_DATA_ADAPTER_USERNAME}
            - DB_DATA_ADAPTER_PASSWORD=${DB_DATA_ADAPTER_PASSWORD}
            - DB_DATA_ADAPTER_DRIVER=${DB_DATA_ADAPTER_DRIVER}
            - DB_WEBFLOW_URL=${DB_WEBFLOW_URL}
            - DB_WEBFLOW_SCHEME=${DB_WEBFLOW_SCHEME}
            - DB_WEBFLOW_USERNAME=${DB_WEBFLOW_USERNAME}
            - DB_WEBFLOW_PASSWORD=${DB_WEBFLOW_PASSWORD}
            - DB_WEBFLOW_DRIVER=${DB_WEBFLOW_DRIVER}
            - POWERAUTH_DATA_ADAPTER_URL=${POWERAUTH_DATA_ADAPTER_URL}
            - POWERAUTH_NEXTSTEP_URL=${POWERAUTH_NEXTSTEP_URL}
            - POWERAUTH_SERVICE_URL=${POWERAUTH_SERVICE_URL}
            - POWERAUTH_SERVICE_SECURITY_TOKEN=${POWERAUTH_SERVICE_SECURITY_TOKEN}
            - POWERAUTH_SERVICE_SECURITY_SECRET=${POWERAUTH_SERVICE_SECURITY_SECRET}
            - POWERAUTH_PUSH_SERVER_URL=${POWERAUTH_PUSH_SERVER_URL}
        depends_on:
            powerauth-nextstep:
                condition: service_healthy
            powerauth-java-server:
                condition: service_healthy
