version: '2.1'
services:

    # PowerAuth 2.0 Server Database
    powerauth-mysql:
        image: powerauth-mysql
        container_name: powerauth-mysql
        ports:
            - "23316:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - /var/lib/powerauth/mysql:/var/lib/mysql
        healthcheck:
            test: mysqladmin -uroot -proot ping
            interval: 5s
            timeout: 5s
            retries: 30

    # PowerAuth 2.0 Server
    powerauth-java-server:
        image: powerauth-java-server
        container_name: powerauth-java-server
        ports:
            - "20010:8080"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/powerauth-java-server"]
            interval: 10s
            timeout: 10s
            retries: 5
        depends_on:
            powerauth-mysql:
                condition: service_healthy

    # PowerAuth 2.0 Admin
    powerauth-admin:
        image: powerauth-admin
        container_name: powerauth-admin
        ports:
            - "20020:8080"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/powerauth-admin"]
            interval: 10s
            timeout: 10s
            retries: 5
        depends_on:
            powerauth-java-server:
                condition: service_healthy

    # PowerAuth 2.0 Push Server Database
    powerauth-push-mysql:
        image: powerauth-push-mysql
        container_name: powerauth-push-mysql
        ports:
            - "23336:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - /var/lib/powerauth/mysql-push:/var/lib/mysql
        healthcheck:
            test: mysqladmin -uroot -proot ping
            interval: 5s
            timeout: 5s
            retries: 30

    # PowerAuth 2.0 Push Server
    powerauth-push-server:
        image: powerauth-push-server
        container_name: powerauth-push-server
        ports:
            - "20030:8080"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/powerauth-push-server"]
            interval: 10s
            timeout: 10s
            retries: 5
        depends_on:
            powerauth-push-mysql:
                condition: service_healthy
            powerauth-java-server:
                condition: service_healthy

    # PowerAuth 2.0 Standard RESTful API Server
    powerauth-rest-api:
        image: powerauth-rest-api
        container_name: powerauth-rest-api
        ports:
            - "18080:8080"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/powerauth-rest-api"]
            interval: 10s
            timeout: 10s
            retries: 5
        depends_on:
            powerauth-java-server:
                condition: service_healthy
